### ISSUE TITLE
added "condense/frontend" branch

### ISSUE THREAD

**Issue by ratalla816** [ratalla816/animal-app#16]
added "condense/frontend" branch to write all the HTML code on index.html, and delete the modal.html files. 
Once the the HTML is consolidated on index.html, condense/frontend will be merged with feature/frontend.

**Comment by UltimateOjo** [comment]
Since we want to consolidate to code on index.html does that mean we copy and paste all the code to the index.html? Or do we use domain elements, event listeners and functions to re create what we have? I’m thinking about just doing the second option.
